spring.application.name=posts-service
spring.profiles.active=dev

resilience4j.retry.instances.comments.maxAttempts=5
resilience4j.retry.instances.comments.waitDuration=1000ms
#resilience4j.retry.instances.comments.enableExponentialBackoff=true
#resilience4j.retry.instances.comments.exponentialBackoffMultiplier=2.0